### ISSUE TITLE
Customizing and Testing this

### ISSUE THREAD

**Issue by c0pp3r** [Tiars/Generic_SWGEmu_Launcher#1]
Tiars - First thanks so much for doing this. What a great addition to the community and so helpful for server admins. 

I've downloaded the project and have it in visual studio but I'm at a loss for a few things.
1. How can I run this inside of VS. I'm noticing it uses a lot of registry keys that are obviously not set since no install occurred
2. Where is the install functionality? Does this part need to be added manually?
3. You have already done a ton of work so I feel like asking for more is abusive but to fully make this something people can utilize some basic customization instructions might get this to the "plug and play" point I feel like you are intending. As I said you have done TONS of work already and this should save someone a lot of time but I feel like some basic pointers would allow them to get up to speed faster.

**Comment by Tiars** [comment]
It is a Work in Progress. When it is complete all of these issues will have been taken care of.
